Fix for PHP 8 deprecation
PHP 8 now generates an exception:

Exception: Deprecated Functionality: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated

This casts the $css to a string so a null will end up being a blank string and not generate the deprecation warning.